# Dependencies
markdown:     rdiscount
pygments:     true

# Permalinks
permalink:    pretty

# Server
destination:  ./_gh_pages
port:         9003

exclude:      ["*.zip", "browserstack.json", "node_modules", "twbs", "temp-css", "sass", "less", ".editorconfig", "composer.json", ".ruby-version", ".gitignore", "bower.json", "config.rb", "Gemfile", "Gruntfile.js", "package.json", "Makefile", "Rakefile", "LICENSE", "README.md", "CONTRIBUTING.md", "requirements.txt"]


## CUSTOM VARS
repo:               https://github.com/alademann/sass-bootstrap
download:           https://github.com/alademann/sass-bootstrap/zipball/master
download_dist:      https://github.com/alademann/sass-bootstrap/blob/master/sass-bootstrap-dist.zip

issues_open:        https://github.com/alademann/sass-bootstrap/issues?state=open
issues_new:         https://github.com/alademann/sass-bootstrap/issues/new

# Misc Vars
ga_id:              UA-39735819-1
app_name:           Sass Bootstrap
current_version:    3.0.1